### ISSUE TITLE
var to const and back

### ISSUE THREAD

**Issue by esraajb** [esraajb/Express-server-GithubAPI#3]
* changing the ' var body = JSON.parse(body); '  to ' const body = JSON.parse(body);' give an error: ' body is not defined'.
 cant find the reason yet. but it doesnt work with let or const. only with var!

**Comment by esraajb** [comment]
@amirma2020

**Comment by amirma2020** [comment]
@esraajb checking

**Comment by amirma2020** [comment]
This exactly the reason why you should use const or let.
Please note that:
the variable you are parsing is with the name body this why is not working with const or let
and working with var.

its similar to:
var body = {}
var body = JSON.parse(body);
and it wont work for const or let.

This is one of the reasons why you should use cnost/let in your app

so, you just need to change it to :
body = JSON.parse(body);
without declaration because it have been declared in the function signature  

take a break, jump to google and see what is the differences between var const and let.
